# Copyright (c) 2018 Bart Massey
# [This program is licensed under the "MIT License"]
# Please see the file LICENSE in the source
# distribution of this software for license terms.

CPP = g++
CPPFLAGS = -g -Wall

randline: randline.o
	$(CPP) $(CPPFLAGS) -o randline randline.o

clean:
	-rm -f randline.o randline
